feat: add unique path for storage file
newrelic/infra-integrations-sdk pull request #260
Opened 2021-03-22 11:32 UTC by cristianciutea

This PR will:
- add unique ID for integration instance based on integration cmd line arguments
- use the unique ID when creating the file for rate/delta storage (this will avoid collision issues when using discovery)
- add entityKey as a namespace attribute to the metric set

2021-03-30 07:28 UTC, gsanchezgavier requested changes
could you merge to v3 branch. I've already ported the jmx bug fix to that one

2021-03-30 13:44 UTC, gsanchezgavier commented on integration/integration.go
> +	h.Write([]byte(fmt.Sprintf("%v", i.args)))
are the configurations passed as environment variables inside args? I'm thinking of the conifguration sample for k8s that the integrations have it only uses env-vars to pass conifgurations and no cli args.

2021-03-30 13:46 UTC, gsanchezgavier commented on integration/integration_test.go
> +func TestIntegration_CreateUniqueID_EnvironmentVar(t *testing.T) {
looks like this ut responds my question above :) nice

2021-03-31 07:36 UTC, varas commented on integration/integration.go
> +	h := md5.New()
not big deal, as integrations won't have enough instances to collide, but in case they did this may be a good option https://github.com/google/uuid

2021-03-31 07:44 UTC, varas approved these changes
![](https://media.giphy.com/media/S6qkS0ETvel6EZat45/giphy.gif)

2021-04-06 15:12 UTC, merged